---
title: "R Notebook"
output: html_notebook
---
```{r}
rm(list=ls())
# Execute our custom script for loading packages
source("usePackages.R")
# Name of the packages 
pkgnames <- c("caret", "e1071","caTools", "class")
# Use our custom load function
loadPkgs(pkgnames)

# Set seed
seed <- 41
```
# Import Data
```{r}
safety <- read.csv("./train1_preprocessed.csv")
test <- read.csv("./test1_preprocessed.csv")
```


```{r}
safety <- subset(safety, select = -c(Case, No, Task, Ch1, Ch2, Ch3, Ch4, CC4, BU4, RP4, LD4, BZ4, FC4, PP4, KA4, SC4, TS4, NV4, Price4))

set.seed(seed)
trainingIndex <- createDataPartition(y = safety$Choice, times = 1, p = 0.8, list = FALSE)
trainingSet <- safety[trainingIndex,]
testSet <- safety[-trainingIndex,]
```

```{r}
classifier_knn <- knn(train = trainingSet,
                      test = testSet,
                      cl = trainingSet$Choice,
                      k = 9)
classifier_knn
```

```{r}
cm <- table(testSet$Choice, classifier_knn)
cm
```

```{r}
misClassError <- mean(classifier_knn != testSet$Choice)
print(paste('Accuracy =', 1-misClassError))
```

