---
title: "Preprocess Data"
output: html_notebook
---

# Data Pre-processing
## Import Libraries
```{r}
rm(list=ls())
# Execute our custom script for loading packages
source("usePackages.R")
# Name of the packages 
pkgnames <- c("dplyr")
# Use our custom load function
loadPkgs(pkgnames)
```

## Import Data
```{r}
safety <- read.csv("../input/train1.csv")
str(safety)
head(safety)
```
## Add Choice
```{r}
safety$Choice <- ifelse(safety$Ch1 == 1, 1,
                        ifelse(safety$Ch2 == 1, 2,
                               ifelse(safety$Ch3 == 1, 3,
                                      ifelse(safety$Ch4 == 1, 4, NA))))
table(safety$Choice)
```

## Drop Columns
```{r}
# might have collinearity with miles, milesind and milesa
# might have collinearity with night, nightind and nighta
df <- subset(safety, select = -c(Ch1, Ch2, Ch3, Ch4)) #, Case, No, segment,year,miles,night,ppark,gender,age,educ,region,Urb,income
head(df)
```

## Export
```{r}
# Writing the output to a csv file
write.csv(df, file = "./train1_trying.csv", row.names = FALSE)
```

# Test Data
## Import Test Data
```{r}
safety <- read.csv("../input/test1.csv")
str(safety)
head(safety)
```
## Add Choice
```{r}
safety$Choice <- 0
safety$Ch1 <- 0
safety$Ch2 <- 0
safety$Ch3 <- 0
safety$Ch4 <- 0
```

## Drop Columns
```{r}
# might have collinearity with miles, milesind and milesa
# might have collinearity with night, nightind and nighta
df <- subset(safety, select = -c(Ch1, Ch2, Ch3, Ch4))
head(df)
#, Case, No, segment,year,miles,night,ppark,gender,age,educ,region,Urb,income
```

## Export
```{r}
# Writing the output to a csv file
write.csv(df, file = "./test1_trying.csv", row.names = FALSE)
```
